### ISSUE TITLE
Manage certificates

### ISSUE THREAD

**Issue by adamlc** [WeKnowSports/terraform-provider-kong#16]
It would be great if we could manage certificates through this provider too, we could then use it in combination with the [lets encrypt](https://github.com/paybyphone/terraform-provider-acme) provider for example :)

**Comment by martinivanov** [comment]
You mean the [Dynamic SSL](https://getkong.org/plugins/dynamic-ssl/) plugin?

**Comment by adamlc** [comment]
@martinivanov that got removed in newer versions of Kong. [Certificates are now managed in the admin api](https://getkong.org/docs/0.11.x/admin-api/#certificate-object). You specify a certificate's domain(s) (SNI) so Kong knows which certificates to use.

**Comment by martinivanov** [comment]
@adamlc, I've added support for certificates and SNIs. Take a look at the latest commits. 
I didn't add the SNI optional field support in the certificate resource, as it may turn out to be problematic - deleting a certificate also deletes the referenced SNIs, which may lead to inconsistent tfstate. Anyway, it's just a convenience if you are calling the admin API directly, it should be much of a hassle with terraform.

Usage is as follows:
```terraform
resource "kong_certificate" "cert" {
  cert = "${file("certificate.pem")}"
  key  = "${file("key.pem")}",
}

resource "kong_sni" "sni" {
  name               = "example.com"
  ssl_certificate_id = "${kong_certificate.cert.id}"
}
```

**Comment by adamlc** [comment]
@martinivanov this is awesome thanks! I'll give it a go over the next few days :)

**Comment by adamlc** [comment]
@martinivanov just given this a test and it seems to work OK. There does seem to be one issue however, each time I do a plan the kong_certificate is registering as an in-place update. Meaning according to terraform the certificate has changed each time.

Im testing this with the lets encrypt plugin referenced in the OP. Not sure if the issue lies there or not!

**Comment by martinivanov** [comment]
It seems like and issue with the key formatting. I will look into it.

**Comment by adamlc** [comment]
@martinivanov Did you have any success with this? If theres an issue with string comparison it may be possible to parse the certificates with OpenSSL and compare the cert's id or something. Not really an expert in this area :)

**Comment by martinivanov** [comment]
@adamlc, Please pull the latest changes. The issue was that Kong trims any whitespaces in the key/cert. Now those are ignored by terraform.

**Comment by adamlc** [comment]
@martinivanov it works perfectly now, thanks for fixing that. I think this addition makes it really powerful combined with the lets encrypt plugin, many thanks :D
