### ISSUE TITLE
API Plugin - JWT - uri_param_names

### ISSUE THREAD

**Issue by adamlc** [WeKnowSports/terraform-provider-kong#17]
In the JWT plugin `uri_param_names` doesn't seem to work properly. Maybe because it needs to be an array instead of a string?

```
resource "kong_api_plugin" "integrations-manager-jwt-auth" {
    api = "${kong_api.integrations-manager.id}"
    name = "jwt"

    config = {
        key_claim_name = "iss"
        anonymous = "cc7f150e-657c-477e-805e-e4bacd11eefe"
        secret_is_base64 = false
        uri_param_names = "key"
    }
}
```

**Comment by martinivanov** [comment]
What is the problem exactly? Usually plugin params are provided as comma separated values. It's unclear from the documentation though...

**Comment by adamlc** [comment]
@martinivanov when I try to update the uri_param_names attribute I get 400 Bad Request errors back from Kong. Not sure what the exact error is though.
