### ISSUE TITLE
Consumer Basic Auth Credential - Always tainted password

### ISSUE THREAD

**Issue by adamlc** [WeKnowSports/terraform-provider-kong#18]
When a password is specified its always tainted because Kong returns a hash of the password. I see you've got it down as a TODO in the code, just thought I'd mention it again.

Its fairly straight forward. Its a sha1 hash of the password and consumer_id, [see here](https://github.com/Kong/kong/blob/master/kong/plugins/basic-auth/crypto.lua).

**Comment by martinivanov** [comment]
Fixed in [1fa3d3c](https://github.com/WeKnowSports/terraform-provider-kong/commit/1fa3d3c22b69ec6afa6cb812851b5728f4f8d782).
