### ISSUE TITLE
Official provider?

### ISSUE THREAD

**Issue by ocxo** [WeKnowSports/terraform-provider-kong#2]
Are there any plans to introduce this as an official provider? Something like this would be very useful for us.

**Comment by martinivanov** [comment]
I would be happy to have this as an official provider. I will see what I can do about it.

**Comment by tecnobrat** [comment]
I think the first start @martinivanov is that we need a LICENSE :)

The terraform project is `Mozilla Public License 2.0`, so being compatible with that license will be key in seeing if this can be pulled into an official provider.

**Comment by martinivanov** [comment]
@tecnobrat, I added license information to the repository. I will need some help with this though. What else should be taken into account?

**Comment by tecnobrat** [comment]
Hey @martinivanov 

I'm not a member of the hashicorp / terraform team at all, just a huge user / fan.

So with the provider splitout that is happening on terraform soon, this should be a good opportunity to see how this will work for us.  @fromonesrc and I work at the same place, so we will be definitely interested in this.  The splitout should make it easy to consume this provider without it being compiled as part of the base project.

I've not tried the release candidate yet, but my understanding is that third-party modules will be easy to use.

**Comment by erran** [comment]
@martinivanov I noticed today that [kevholditch/terraform-provider-kong](https://github.com/kevholditch/terraform-provider-kong) is listed on the [Terraform community providers list](https://www.terraform.io/docs/providers/type/community-index.html) page.

I'll submit my patches to this provider e.g. #12, #13, #14, and #15. As well as any changes that I hadn't submitted to WeKnowSports/terraform-provider-kong yet. [`WeKnowSports:abb86cd...rapid7:8169946`](https://github.com/WeKnowSports/terraform-provider-kong/compare/WeKnowSports:abb86cd...rapid7:8169946#diff-d7e859c9cf11230365328fcecbd5ffbd) (sorry about not putting a PR for those yet, been busy using it!)

It'd be great if WeKnowSports @martinivanov, rapid7 @erran, and @kevholditch could collaborate on getting a single solution that meets all our needs.
