### ISSUE TITLE
Feature request: add http basic auth support

### ISSUE THREAD

**Issue by alza-bitz** [WeKnowSports/terraform-provider-kong#4]
Hi there,

Please would you consider adding support for http basic auth when calling the Kong admin api using the provider? As in, configuring the provider with username and password.

The Kong instance I'm using is configured with basic auth on the Kong admin api, so I'd need basic auth support in order to use this provider.

Thanks,

Alex.

**Comment by martinivanov** [comment]
Hi,

I will add it, but in the meantime you can just put the credentials in the address

``
provider "kong" {
    address = "http://username:password@192.168.99.100:8001"
}
``

I think it should work this way.
